### ISSUE TITLE
src binding issue

### ISSUE THREAD

**Issue by motss** [PolymerElements/iron-image#39]
The `iron-image` element does not display the image correctly.

### [sample and demo code for the issue](https://github.com/motss/image-src-binding-issue)

![Screenshot showing wrong image location if binding is used](https://cloud.githubusercontent.com/assets/10607759/11180739/1de6c020-8c98-11e5-9730-0ab8f60907ee.png)
## Expected outcome

Loads and displays image from `src`.

## Actual outcome

The `iron-image` element only displays image correctly when `src` is set declaratively.
It seems like `src` has a wrong image location if compound binding or property binding is used.

## Steps to reproduce

1. Set up `src` declaratively and `iron-image` loads and displays image correctly.
2. Use compound-binding or property binding for the value of `src` and `iron-image` fails to display any image.

**Comment by bicknellr** [comment]
This is actually working as expected (aside from #23):

[`Polymer.ResolveUrl.resolveUrl`](https://github.com/Polymer/polymer/blob/a2e2a118bab73ec3b31b654adf474252d5cb6194/src/lib/resolve-url.html#L26-L41) takes attributes which typically contain URLs and resolves their values relative to the owner document of the `dom-module` declaring your element. However, this transformation is only performed at create time and only if the attribute does not contain a binding.

```
image-src-binding-issue.html
demo/
- index.html
img/
- owl.jpg
```

The first `iron-image` works because `img/owl.jpg` contains no binding and resolves relative to `image-src-binding-issue.html` at create.

For the second and third `iron-image`, the attributes are not resolved at create because they contain bindings. When they are interpolated *after* create, they aren't resolved to an absolute URL but remain relative to `demo/index.html` instead - the document which instantiated the `image-src-binding-issue` and its contained `iron-image` elements. If you prefix the `src` attributes containing bindings with `../` (and remove the `preload` attribute from the second and third `iron-image`, because of #23), then all three will load.

`Polymer.ResolveUrl.resolveUrl` is the same function that Polymer uses to resolve URLs relative to a given document. If you need to use a binding to pass a URL, but want that URL to be resolved against the document declaring your element, that function will do it for you.

**Comment by bicknellr** [comment]
This is definitely some confusing behavior though and deserves some documentation. I'll file an issue with the core library.
