### ISSUE TITLE
loaded property change multiple times inside iron-list

### ISSUE THREAD

**Issue by JohnsonChung** [PolymerElements/iron-image#73]
### Description
When use the `<iron-image>` element  inside `<iron-list>`, `iron-image loaded` property change multiple times when scrolling page.
I understand that iron-list will detach element when that out of the window for a distance. 

### Expected outcome
I expected `on-loaded-changed` will fire *only once* when an image was full loaded.

### Actual outcome
`on-loaded-changed` event observer will fire multiple times when scrolling back and forth.

### Live Demo
[https://jsbin.com/dirazo/edit?html,console,output](https://jsbin.com/dirazo/edit?html,console,output)

**Comment by davidrissato** [comment]
Johnson: this behavior is expected, due to the way iron list works.

I made a change to your example so we can watch loaded-changed being called with values true and false in order to explain. Take a look here: https://jsbin.com/mixoqorino/2/edit?html,console,output

Iron list is an extermelly smart piece of software, and it wont render your entire list at once. Whenever you scroll up or down, it replaces some instances of your template with new values, including your images.

This is why it keeps popping loaded-changed messages: iron-list just unloaded an image that was out of the screen and loaded a new one using the same iron-image object.

If you need just a simple list, without this kind of control provided by iron-list, you can use a simple dom-repeater instead, and you will get the behavior you wanted. However, if your list is too large, rendering all elements at once can lead to slowness and huge memory consumption depending on the size of your list.

Regards,
David
