### ISSUE TITLE
Image not displayed in the content of a <paper-header-panel> when using sizing

### ISSUE THREAD

**Issue by Pixinn** [PolymerElements/iron-image#75]
### Description

Chrome 50 and the latest Safari on OSX won't display an _iron-image_ inside the "content area" of a _paper-header-panel_ if its **sizing** attribute is set.
Firefox 46, Edge and IE11 all display the image properly.

Here you can find a simple test-page affected : [https://pub.xtof.info/iron-image/ko/](https://pub.xtof.info/iron-image/ko/)

If an absolute positioning is applied to the iron-image, it will be properly displayed in all browsers.
See:  [https://pub.xtof.info/iron-image/ok/](https://pub.xtof.info/iron-image/ok/)

**Comment by bicknellr** [comment]
Hi @Pixinn, I asked @notwaldorf about this and she made a demo which I modified a bit [here](http://jsbin.com/kahabo/1/edit?html,output) showing that this isn't an iron-image issue but rather a flex issue.

Unfortunately, there doesn't seem to be any consistency about what happens in this situation:

| Chrome / Safari | Firefox / IE |
|---|---|
| ![screen shot 2016-05-10 at 16 52 58](https://cloud.githubusercontent.com/assets/406614/15166032/b3017f8a-16cf-11e6-80b8-5c3240184a5b.png) | ![screen shot 2016-05-10 at 16 52 52](https://cloud.githubusercontent.com/assets/406614/15166033/b7c669ae-16cf-11e6-8db5-2be9f02e9cda.png) |

I've been trying to wrap my head around the spec but haven't been able to figure out much. Maybe there's some weirdness with intrinsic / extrinsic sizing and flex items? I'm going to close this because it's not really an iron-image issue, but @ojanvafai might have some insight to share here about flex.
